#!/bin/bash
# this code was written by zwerd
engine=$1
url=$2
dirc=$3
options=$4
# How to run the script:
[ $# -eq 0 ] && { 
echo "Usage: $0 <buster engine> <url> <dir> <options>"; 
echo "Buster Engine: dirb, dirbuster, gobuster, dirsearch, feroxbuster."
echo "Directories: dirb, dirbuster, xajkep/discovery, seclists."
echo "Options: -k html, -d, -e etc."
echo "Note: options -u , -w, and -o already used, so don't use them."
exit 1; }

for dir in $(ls -laS $(find /usr/share/wordlists/$dirc/* | grep txt)|awk '{print $9}');
do 
	echo "dir: $dir"
	echo "url: $url"
	echo $url |sed 's/.*\://'|cut -d"/" -f3
	echo "run: $engine -u $url -w $dir -o $(pwd)/$(echo $engine)_$(echo $url |sed 's/.*\://'|cut -d"/" -f3)_$(echo $dir|awk -F"/" '{print $NF}') $options"
	$engine -u $url -w $dir -o $(pwd)/$(echo $engine)_$(echo $url |sed 's/.*:\://'|cut -d"/" -f3)_$(echo $dir|awk -F"/" '{print $NF}') $options
	sleep 5
done
